import type { CanonicalSource } from '@/types/canonical';

const sources = new Map<string, CanonicalSource>();

export function getSource(id: string): CanonicalSource | undefined {
  return sources.get(id);
}

export function getAllSources(): CanonicalSource[] {
  return Array.from(sources.values());
}

export function getSourcesByEntity(entityId: string): CanonicalSource[] {
  return Array.from(sources.values()).filter(
    s => s.claimIds.some(cid => cid.includes(entityId))
  );
}

export function registerSource(source: CanonicalSource): void {
  sources.set(source.id, source);
}

export function seedSources(): void {
  const seed: CanonicalSource[] = [
    {
      id: 's1',
      title: 'India After Gandhi: The History of the World\'s Largest Democracy',
      tier: 3,
      accessedAt: '2026-06-15',
      claimIds: [
        'claim.partition.security-consciousness',
        'claim.kashmir.un-referral',
        'claim.nonalignment.strategic-autonomy',
        'claim.secular-nationalism.foreign-policy',
        'claim.partition.founding-trauma',
        'claim.partition.refugee-crisis',
        'claim.partition.princely-states',
        'claim.partition.division-of-assets',
        'claim.partition.minorities',
        'claim.partition.demographic-impact',
        'claim.partition.economic-impact',
        'claim.partition.security-paradigm',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's3',
      title: 'Partition of India: A Historical Survey',
      tier: 3,
      accessedAt: '2026-06-20',
      claimIds: [
        'claim.partition.security-consciousness',
        'claim.kashmir.un-referral',
        'claim.partition.refugee-crisis',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's4',
      title: 'Jawaharlal Nehru, Speech to Constituent Assembly, 1946',
      tier: 1,
      accessedAt: '2026-06-20',
      claimIds: ['claim.secular-nationalism.foreign-policy'],
      documentIds: ['doc-nehru-tryst'],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's5',
      title: 'Freedom at Midnight',
      tier: 3,
      accessedAt: '2026-06-20',
      claimIds: [],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's6',
      title: 'UN Security Council Resolution 47 (1948)',
      tier: 1,
      accessedAt: '2026-06-22',
      claimIds: ['claim.kashmir.un-referral'],
      documentIds: ['doc-un-res-47'],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's7',
      title: 'Nehru: The Invention of India',
      tier: 3,
      accessedAt: '2026-06-22',
      claimIds: [
        'claim.nonalignment.strategic-autonomy',
        'claim.secular-nationalism.foreign-policy',
        'claim.partition.founding-trauma',
        'claim.partition.nehru-patel-dynamic',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's8',
      title: 'The Kashmir Dispute: A Historical Introduction',
      tier: 3,
      accessedAt: '2026-06-22',
      claimIds: ['claim.kashmir.un-referral'],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's9',
      title: 'Census of India, 1941',
      tier: 1,
      accessedAt: '2026-06-20',
      claimIds: ['claim.partition.demographic-impact'],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's10',
      title: 'Partition Violence: An Empirical Account',
      tier: 2,
      accessedAt: '2026-06-23',
      claimIds: ['claim.partition.security-consciousness'],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's11',
      title: 'Indian Independence Act, 1947',
      url: 'https://example.com/indian-independence-act-1947',
      tier: 1,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.founding-trauma',
        'claim.partition.division-of-assets',
        'claim.partition.princely-states',
      ],
      documentIds: ['doc-independence-act'],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's12',
      title: 'Mountbatten Plan (3 June 1947)',
      url: 'https://example.com/mountbatten-plan',
      tier: 1,
      accessedAt: '2026-07-12',
      claimIds: ['claim.partition.founding-trauma'],
      documentIds: ['doc-mountbatten-plan'],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's13',
      title: 'Radcliffe Award (17 August 1947)',
      url: 'https://example.com/radcliffe-award',
      tier: 1,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.founding-trauma',
        'claim.partition.division-of-assets',
      ],
      documentIds: ['doc-radcliffe-award'],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's14',
      title: 'Instrument of Accession of Jammu and Kashmir (26 October 1947)',
      url: 'https://example.com/instrument-of-accession-kashmir',
      tier: 1,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.kashmir.accession-disputed',
        'claim.partition.princely-states',
      ],
      documentIds: ['doc-kashmir-accession'],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's15',
      title: 'Liaquat-Nehru Pact, 1950',
      url: 'https://example.com/liaquat-nehru-pact',
      tier: 1,
      accessedAt: '2026-07-12',
      claimIds: ['claim.partition.minorities'],
      documentIds: ['doc-liaquat-nehru-pact'],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's16',
      title: 'The Great Partition: The Making of India and Pakistan',
      url: 'https://example.com/great-partition',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.founding-trauma',
        'claim.partition.refugee-crisis',
        'claim.partition.violence-civil-society',
        'claim.partition.minorities',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's17',
      title: 'The Sole Spokesman: Jinnah, the Muslim League and the Demand for Pakistan',
      url: 'https://example.com/sole-spokesman',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.avoidable',
        'claim.partition.nehru-patel-dynamic',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's18',
      title: 'The Story of the Integration of the Indian States',
      url: 'https://example.com/integration-indian-states',
      tier: 2,
      accessedAt: '2026-07-12',
      claimIds: ['claim.partition.princely-states'],
      documentIds: ['doc-integration-states'],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's19',
      title: 'Remembering Partition: Violence, Nationalism and History in India',
      url: 'https://example.com/remembering-partition',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.violence-civil-society',
        'claim.partition.memory',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's20',
      title: 'The Other Side of Silence: Voices from the Partition of India',
      url: 'https://example.com/other-side-silence',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.violence-civil-society',
        'claim.partition.gender',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's21',
      title: 'Midnight\'s Furies: The Deadly Legacy of India\'s Partition',
      url: 'https://example.com/midnights-furies',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.security-paradigm',
        'claim.partition.founding-trauma',
        'claim.partition.kashmir-unfinished',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's22',
      title: 'Jawaharlal Nehru: A Biography (3 vols)',
      url: 'https://example.com/s-gopal-nehru',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.nehru-patel-dynamic',
        'claim.partition.founding-trauma',
        'claim.nonalignment.origins',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's23',
      title: 'Conflict Unending: India-Pakistan Tensions Since 1947',
      url: 'https://example.com/conflict-unending',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.security-paradigm',
        'claim.partition.kashmir-unfinished',
        'claim.partition.relations-pakistan-permanent',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's24',
      title: 'Crossing the Rubicon: The Shaping of India\'s New Foreign Policy',
      url: 'https://example.com/crossing-rubicon',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.nonalignment.strategic-autonomy',
        'claim.partition.security-paradigm',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's25',
      title: 'India: Emerging Power',
      url: 'https://example.com/india-emerging-power',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.security-paradigm',
        'claim.partition.relations-pakistan-permanent',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's26',
      title: 'Bengal Divided: Hindu Communalism and Partition, 1932-1947',
      url: 'https://example.com/bengal-divided',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.avoidable',
        'claim.partition.demographic-impact',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's27',
      title: 'The Punjab Bloodied, Partitioned and Cleansed',
      url: 'https://example.com/punjab-bloodied',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.violence-civil-society',
        'claim.partition.demographic-impact',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's28',
      title: 'Pakistan: A Hard Country',
      url: 'https://example.com/pakistan-hard-country',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.relations-pakistan-permanent',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's29',
      title: 'The Garrison State: Military, Government and Society in Colonial Punjab, 1849-1947',
      url: 'https://example.com/garrison-state',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.division-of-assets',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's30',
      title: 'Making Sense of Pakistan',
      url: 'https://example.com/making-sense-pakistan',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.relations-pakistan-permanent',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
    {
      id: 's31',
      title: 'Divided Cities: Partition and Its Aftermath in Lahore and Amritsar',
      url: 'https://example.com/divided-cities',
      tier: 3,
      accessedAt: '2026-07-12',
      claimIds: [
        'claim.partition.refugee-crisis',
      ],
      documentIds: [],
      chapterIds: ['kl-ch-1'],
      thinkerIds: [],
      storyIds: [],
      datasetIds: [],
    },
  ];

  for (const s of seed) sources.set(s.id, s);
}
