import type { TBSStory } from '@/types/canonical';

const story: TBSStory = {
  id: 'rbi-monetary-policy-hold-2026',
  slug: 'rbi-monetary-policy-hold-2026',
  storyType: 'Policy Analysis',
  title: 'The RBI Inflation Dilemma: Why Holding Rates Could Matter More Than Cutting Them',
  subtitle: 'As inflation eases toward target, the RBI faces its hardest decision: cut too soon and risk a price spiral, hold too long and deepen a slowdown',
  hero: {
    image: '',
    statistic: '6.5% ↓ 4% ↓ ₹50L',
    statisticSource: 'Repo Rate → Inflation Target → Example Home Loan',
    caption: 'The RBI holds rates at 6.5% while inflation approaches the 4% target, keeping a ₹50 lakh home loan EMI high',
    altText: 'RBI Monetary Policy Committee in session, Governor at the press conference',
    credit: 'RBI / Reuters Editorial',
    aspectRatio: '16:9',
  },
  summary: 'The Reserve Bank of India is widely expected to hold the repo rate steady at 6.5% in its upcoming review, continuing a cautious stance as policymakers weigh moderating inflation against persistent and rising growth risks. The RBI is keeping interest rates high because reducing inflation too early could create larger problems later — a dilemma that affects every borrower, saver, and investor in India.',
  keyFacts: [
    { claim: 'Repo rate held at 6.5% across recent reviews', source: 'RBI Monetary Policy Statements', confidence: 1 },
    { claim: 'Inflation has been moderating toward the 4% target', source: 'RBI Annual Report; MOSPI', confidence: 1 },
    { claim: 'Growth risks have increased; GDP projections revised downward', source: 'IMF World Economic Outlook; Reuters Poll', confidence: 1 },
    { claim: 'Reuters poll expects RBI to hold rates through 2026', source: 'Reuters (July 27, 2026)', confidence: 2 },
  ],
  metadata: {
    difficulty: 'Intermediate',
    confidence: 'Medium',
    confidenceRationale: 'RBI policy stance from press releases is high-confidence; growth and inflation projections from Reuters poll of economists (July 2026); specific GDP and inflation figures for FY27 are projections subject to revision',
    updateRequired: true,
    readingTimeMinutes: 8,
    tags: ['rbi', 'monetary-policy', 'repo-rate', 'inflation', 'interest-rates', 'india-economy'],
    entities: [
      { name: 'Reserve Bank of India', type: 'institution', role: 'primary' },
      { name: 'Monetary Policy Committee', type: 'committee', role: 'decision-maker' },
      { name: 'Repo Rate', type: 'economic-indicator', role: 'key-rate' },
      { name: 'Inflation', type: 'economic-indicator', role: 'target-variable' },
    ],
    lastVerified: '2026-07-29',
    nextVerificationDue: '2026-10-29',
  },
  whyItMatters: 'The RBI interest rate decision directly affects the cost of borrowing for millions of Indians — homebuyers, businesses, and governments. When rates stay high, credit is expensive, dampening investment. When rates are cut too aggressively, inflation can spiral. Getting the timing right is one of the most consequential decisions in Indian economic governance.',
  narrative: 'The Reserve Bank of India Monetary Policy Committee is widely expected to hold the repo rate unchanged at its upcoming review, continuing a cautious stance as moderating inflation and persistent external headwinds create a balancing act between price stability and growth support.',
  timeline: [
    { date: 'Feb 2025', event: 'RBI begins rate pause after hiking cycle', source: 'RBI Monetary Policy Statements', significance: 'After a series of hikes, the MPC stops raising rates' },
    { date: 'Mid-2025', event: 'Inflation approaches 4% target', source: 'RBI Annual Report', significance: 'Inflation comes within the target band' },
    { date: 'Late 2025', event: 'Global growth risks intensify', source: 'IMF World Economic Outlook; RBI Annual Report', significance: 'External headwinds increase' },
    { date: '2026', event: 'RBI holds repo rate through multiple reviews', source: 'RBI Press Releases', significance: 'Accommodative stance maintained' },
    { date: 'Jul 27, 2026', event: 'Reuters poll expects RBI to hold rates through 2026', source: 'Reuters', significance: 'Economists poll reaffirms hold stance' },
  ],
  systemExplanation: {
    headline: 'How the RBI Sets Interest Rates',
    summary: 'The RBI Monetary Policy Committee meets every two months to decide the repo rate — the rate at which the RBI lends to commercial banks. Changes ripple through the entire economy, influencing borrowing costs, spending, and investment.',
    steps: [
      { label: '1. Inflation data reviewed', description: 'The MPC examines CPI and WPI data, comparing actual inflation to the 4% target.', actor: 'RBI Statistics Department' },
      { label: '2. Growth outlook assessed', description: 'The MPC reviews GDP growth projections, industrial production data, and employment figures.', actor: 'RBI Research Department' },
      { label: '3. Global conditions evaluated', description: 'Commodity prices, global interest rates, foreign capital flows, and exchange rates are considered.', actor: 'RBI Research Department' },
      { label: '4. Vote taken by MPC', description: 'The six-member committee votes by majority. The Governor casts a deciding vote if tied.', actor: 'Monetary Policy Committee (6 members)' },
      { label: '5. Repo rate held or adjusted', description: 'A hike makes borrowing expensive (slowing activity, fighting inflation). A cut stimulates growth (risking inflation). A hold maintains the current balance.', actor: 'RBI; Commercial Banks; Market' },
      { label: '6. Transmission to economy', description: 'The repo rate flows through bank lending rates, bond yields, housing finance rates, affecting consumer spending and business investment.', actor: 'Commercial Banks; Financial Markets; Households; Businesses' },
    ],
    diagram: '/images/diagrams/repo-rate-transmission.svg',
    diagramAlt: 'Flow diagram showing how RBI repo rate changes transmit through banks and markets',
  },
  evidence: [
    { claim: 'Repo rate held at 6.5% across recent reviews', source: 'RBI Monetary Policy Statements', confidence: 1, verifiedAt: '2026-07-29' },
    { claim: 'Inflation has been moderating toward the 4% target', source: 'RBI Annual Report; MOSPI', confidence: 1, verifiedAt: '2026-07-29' },
    { claim: 'Growth risks increased; GDP projections revised downward', source: 'IMF World Economic Outlook; Reuters Poll (Jul 2026)', confidence: 1, verifiedAt: '2026-07-29' },
    { claim: 'Reuters poll expects RBI to hold rates through 2026', source: 'Reuters (July 27, 2026)', confidence: 2, verifiedAt: '2026-07-27' },
    { claim: 'Global financial conditions tightened, affecting emerging market flows', source: 'IMF Global Financial Stability Report', confidence: 1, verifiedAt: '2026-07-29' },
  ],
  charts: [
    { title: 'Repo Rate Trajectory (2024–2026)', type: 'line', data: [{ label: 'Jan 2024', value: 6.5 }, { label: 'Jul 2026 (expected)', value: 6.5 }], source: 'RBI' },
  ],
  stakeholders: {
    headline: 'Stakeholder Analysis',
    stakeholders: [
      { name: 'Reserve Bank of India', type: 'institution', position: 'Sets monetary policy', interest: 'Price stability and financial stability', stance: 'neutral' },
      { name: 'Monetary Policy Committee', type: 'committee', position: 'Decides repo rate by majority vote', interest: 'Balancing inflation control with growth support', stance: 'neutral' },
      { name: 'Commercial Banks', type: 'private_sector', position: 'Lend to consumers and businesses', interest: 'Net interest margin and asset quality', stance: 'conditional' },
      { name: 'Homebuyers', type: 'consumer', position: 'Borrowers in housing market', interest: 'Affordable EMIs', stance: 'oppose' },
      { name: 'Government of India', type: 'government', position: 'Borrows through government securities', interest: 'Fiscal cost control and growth', stance: 'conditional' },
      { name: 'Consumers and Households', type: 'consumer', position: 'Savers and borrowers broadly', interest: 'Cost of living and purchasing power', stance: 'neutral' },
      { name: 'Export Sector', type: 'industry', position: 'Indian exporters', interest: 'Exchange rate competitiveness', stance: 'neutral' },
      { name: 'International Investors', type: 'institution', position: 'Foreign portfolio investors', interest: 'Yield differential and liquidity', stance: 'neutral' },
    ],
    summary: 'The primary tension is between price stability and the economy need for low borrowing costs. Consumers benefit most from rate cuts; the RBI independence and inflation-targeting framework create constraints.',
  },
  perspectives: {
    headline: 'Multiple Perspectives',
    perspectives: [
      { label: 'RBI / MPC', source: 'RBI Policy Statements', quote: 'The Committee has been mindful of both upside and downside risks and will continue to monitor inflation dynamics and growth indicators closely.', stance: 'Hold is appropriate' },
      { label: 'Government of India', source: 'Ministry of Finance', quote: 'The government supports the RBI independent stance and remains focused on structural reforms.', stance: 'Neutral' },
      { label: 'Economists (Bullish on Hold)', source: 'Bloomberg consensus; RBI research', quote: 'Premature easing could destabilize inflation expectations, which have been well-anchored near 4%.', stance: 'support_hold' },
      { label: 'Economists (Bullish on Cuts)', source: 'IMF Country Report; Morgan Stanley', quote: 'Growth risks are asymmetric — the cost of waiting too long to ease policy is a deeper recession.', stance: 'oppose_hold' },
      { label: 'Industry (ASSOCHAM, CII, FICCI)', source: 'Industry body statements', quote: 'Industrial production and new export orders have softened. The private sector needs lower borrowing costs.', stance: 'conditional_support' },
      { label: 'International Organizations', source: 'IMF Article IV; World Bank', quote: 'India inflation has improved materially, but the growth outlook has deteriorated. The IMF supports a data-dependent approach.', stance: 'neutral' },
    ],
    note: 'The RBI policy is deliberately data-dependent and opaque, meaning markets must interpret signals from biannual policy statements rather than receive explicit forward guidance.',
  },
  tradeoffs: [
    { option: 'Hold rates (current path)', benefits: ['Inflation within target band', 'Inflation expectations anchored', 'No surprise shifts that could unhinge markets', 'RBI retains flexibility'], risks: ['High borrowing costs suppress investment', 'Housing market subdued', 'Consumer spending slows', 'Growth weakens if headwinds persist'], evidence: 'RBI Monetary Policy Statements; IMF World Economic Outlook' },
    { option: 'Cut rates gradually', benefits: ['Signals a pivot without breaking framework', 'Provides relief to credit-dependent sectors', 'Maintains buffer if inflation re-accelerates'], risks: ['Gradual cuts may be insufficient', 'Markets may interpret ambiguity as indecisiveness'], evidence: 'Historical gradual easing cycles in India' },
  ],
  futureOutlook: {
    headline: 'What Happens Next?',
    scenarios: [
      { label: 'Best Case', description: 'Inflation continues moderating, global growth stabilises, and the RBI begins a gradual cutting cycle in H2 FY27, supporting a soft-landing recovery.', probability: '25–35%', source: 'RBI Analysis; IMF Projections' },
      { label: 'Most Likely', description: 'Inflation stable near 4%, growth risks persist, and the RBI holds through 2026, with a cautious cut possible in early 2027.', probability: '50–60%', source: 'Reuters Poll of Economists (Jul 2026)' },
      { label: 'Worst Case', description: 'Inflation re-accelerates from food or commodity shocks while growth weakens, forcing the RBI into a policy bind.', probability: '10–20%', source: 'RBI Risk Assessment; IMF' },
    ],
    uncertainty: 'The biggest uncertainty is global commodity price movements, which directly affect Indian inflation and growth simultaneously.',
    confidence: 'Medium',
  },
  faq: [
    { question: 'What is the repo rate?', answer: 'The repo rate is the rate at which the Reserve Bank of India lends money to commercial banks against government securities. It is the RBI primary tool for controlling liquidity and influencing interest rates.', source: 'RBI Website' },
    { question: 'Why does the RBI target 4% inflation?', answer: 'The RBI Monetary Policy Framework Agreement with the Government of India sets the inflation target at 4%, with a tolerance band of ±2%. Price stability is a prerequisite for sustainable economic growth.', source: 'RBI Act, Section 45ZA' },
    { question: 'How often does the RBI review rates?', answer: 'The Monetary Policy Committee meets at least four times a year, typically every two months.', source: 'RBI Act' },
    { question: 'What happens if the RBI cuts rates?', answer: 'A rate cut reduces borrowing costs for banks, which typically pass the reduction to consumers and businesses through lower lending rates, stimulating investment and consumption.', source: 'RBI Monetary Policy Transmission Mechanism' },
    { question: 'How does the repo rate affect my home loan EMI?', answer: 'Floating-rate home loans in India are typically linked to the repo rate or a bank marginal cost of funds. When the repo rate rises or falls, bank lending rates follow, directly affecting EMI amounts.', source: 'National Housing Bank; RBI Guidelines' },
  ],
  takeaways: [
    'The RBI is expected to hold the repo rate unchanged, maintaining an accommodative stance amid moderating inflation and rising growth risks.',
    'The Monetary Policy Committee balances a dual mandate — price stability and growth support.',
    'The repo rate is the RBI primary tool; changes ripple through banks, bond markets, housing finance, and ultimately every Indian borrower and saver.',
    'The hold decision reflects a data-dependent framework where policy shifts only when incoming evidence warrants a change.',
    'The trade-off is between different risks: premature easing risks reigniting inflation; prolonged holding risks deepening a slowdown.',
  ],
  sources: [
    { title: 'RBI Monetary Policy Statement', author: 'Reserve Bank of India', date: 'Multiple dates 2025–2026', url: 'https://www.rbi.org.in', reliability: 'high' },
    { title: 'RBI Monetary Policy Statement', author: 'Reserve Bank of India', date: 'Multiple dates 2025–2026', url: 'https://www.rbi.org.in', reliability: 'high' },
    { title: 'RBI Monetary Policy Report', author: 'Reserve Bank of India', reliability: 'high' },
    { title: 'Reuters Poll: RBI to Hold Rates Through 2026', author: 'Reuters', date: '2026-07-27', url: 'https://www.reuters.com/world/india/rbi-hold-rates-through-2026-growth-risks-outweigh-inflation-2026-07-27/', reliability: 'high' },
    { title: 'IMF Article IV Consultation: India', author: 'International Monetary Fund', reliability: 'high' },
    { title: 'IMF World Economic Outlook', author: 'International Monetary Fund', date: '2026', reliability: 'high' },
    { title: 'RBI Annual Report', author: 'Reserve Bank of India', reliability: 'high' },
    { title: 'Monetary Policy Framework Agreement (2015)', author: 'RBI; Ministry of Finance', reliability: 'high' },
    { title: 'Consumer Price Index (CPI)', author: 'Ministry of Statistics and Programme Implementation', reliability: 'high' },
  ],
  relatedKnowledge: [
    { title: 'Understanding India Fiscal Deficit', slug: 'india-fiscal-deficit', relation: 'Fiscal policy complements monetary policy' },
    { title: 'How a Bill Becomes Law in India', slug: 'how-a-bill-becomes-law', relation: 'The RBI Act governs the legal framework under which the MPC operates' },
    { title: 'India Union Budget', slug: 'india-union-budget', relation: 'The budget defines fiscal policy that the RBI must consider' },
    { title: 'Reserve Bank of India', slug: 'reserve-bank-of-india', relation: 'Institutional overview of the RBI' },
  ],
  visuals: [
    { section: 'hero', type: 'photograph', placement: 'hero', aspectRatio: '16:9', caption: 'RBI Monetary Policy Committee in session', altText: 'Members of the RBI MPC at a meeting', credit: 'Reuters Editorial' },
    { section: 'Evidence & Data', type: 'chart', placement: 'inline', aspectRatio: '16:9', caption: 'Repo rate held steady across recent policy reviews', altText: 'Line chart showing repo rate stability at 6.5%', credit: 'RBI / The Breakdown' },
    { section: 'Understanding the System', type: 'diagram', placement: 'inline', aspectRatio: '16:9', caption: 'How repo rate changes flow through the economy', altText: 'Process diagram showing monetary policy transmission mechanism', credit: 'The Breakdown (original graphic)' },
    { section: 'Future Outlook', type: 'chart', placement: 'inline', aspectRatio: '16:9', caption: 'Probability-weighted scenario outcomes', altText: 'Three-scenario probability chart', credit: 'The Breakdown / IMF / Reuters' },
  ],
};

export default story;