export type AppPermission =
  // Content & Editorial
  | 'story.read'
  | 'story.create'
  | 'story.update'
  | 'story.publish'
  | 'story.delete'
  | 'investigation.read'
  | 'investigation.write'
  | 'citation.create'
  | 'citation.modify'
  | 'editorial.schedule'
  // Intelligence Bureau
  | 'intel.dashboard'
  | 'intel.watchlist'
  | 'intel.predictions'
  | 'intel.scenarios'
  | 'intel.candidates'
  | 'intel.media'
  | 'intel.research'
  | 'intel.toolkit'
  | 'intel.editorial'
  | 'intel.story_builder'
  | 'intel.verification'
  | 'intel.rti'
  | 'intel.tasks'
  | 'intel.newsroom'
  | 'intel.demand'
  // Administrative & Security
  | 'api_key.read'
  | 'api_key.create'
  | 'api_key.revoke'
  | 'user.role.grant'
  | 'user.role.revoke'
  | 'audit.read'
  | 'system.config';
